### PR TITLE
Update jokes.json

### PR DESCRIPTION
**Pull request by ewatch**
added a new joke about computer scientists

### CODE REVIEW

**Comment by ewatch** [comment]
Sorry didn't recognize the conflicts last time.

Thanks!

**Review by ABSphreak — COMMENTED** [review]
Making waaaayyyyyy too many changes, I think you didn't sync your fork and just copied directly.

**Comment by ABSphreak** [comment]
Try to make the changes or I will merge the changes... but would have to go through a lot and compare the whole thing.

**Comment by ABSphreak** [comment]
https://readme-jokes-git-master.absphreak.vercel.app/api
something is broken I guess?

**Comment by ewatch** [comment]
Mhh let me check.

**Comment by ewatch** [comment]
closed and replaced with this PR:
https://github.com/ABSphreak/readme-jokes/pull/28

**Pull request closed without merging**
