### PR TITLE
I have created a table so anyone who wants to use the cards can get a preview

### PR DESCRIPTION
**Pull request by SrNightmare09**
So basically, before we had to paste every URL of the available themes to see which ones we like the best; however, it took a lot of time. So, I have made a little table (it's huge) where users can see how each theme looks like when implemented in the jokes card. If this pull request is accepted, I will continue to work on more features whihc I have planned about this project, so it can reach out to more people! Glad to help!

PREVIEW 
Screen Shot 2021-06-13 at 3 15 30 AM

### CODE REVIEW

**Review by ABSphreak — APPROVED** [review]
Nice work @SrNightmare09, but some themes nor working issue persists.

**Comment by SrNightmare09** [comment]
> Nice work @SrNightmare09, but "some themes not working" issue persists.

Hmm, as far as I know, I have put in the urls correctly, so its up to you to fix them. also expect another pr soon

**Comment by ABSphreak** [comment]
@SrNightmare09, Issue #43 has been solved now.

**Comment by SrNightmare09** [comment]
> @SrNightmare09, Issue #43 has been solved [here](https://github.com/ABSphreak/readme-jokes/commit/ceed470813dd404fecd79e87ce8dd5df5d1d8af1).

EPIC

**Pull request merged**
