### PR TITLE
Added dev humour in jokes.json

### PR DESCRIPTION
**Pull request by irvine09**

### CODE REVIEW

**Comment by ABSphreak** [comment]
@irvine09 resolve the conflicts and I will merge.

**Review by irvine09 — COMMENTED** [review]
reviewed

**Comment by ABSphreak** [comment]
There are still conflicts, please resolve them @irvine09

**Comment by irvine09** [comment]
thanks @ABSphreak . ive removed single quote which might be breaking the build too. hopefully this new commit will fix the conflict.

**Comment by ABSphreak** [comment]
@irvine09 it's still not passing all the checks.
You can open up a new PR and close this one if you're having issues.
I will add `hacktoberfest-accepted` to that one if it passes the checks and merge it.

This is an active issue #13 

Thank you for your efforts.

**Comment by irvine09** [comment]
Closing due to conflict

**Pull request closed without merging**
